version: "3"

services:
  varnish:
    image: emgag/varnish:6.0.3-2 
    hostname: docker-varnish
    volumes:
      - ${PWD}/etc/varnish:/etc/varnish
      - ${PWD}/run:/tmp/run/
    command: varnishd -j unix,user=vcache -F -f /etc/varnish/default.vcl -s malloc,500M -a 0.0.0.0:8081 -a 0.0.0.0:8082,proxy -a /tmp/run/varnish.sock,proxy -T 0.0.0.0:8083 -p feature=+http2
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on: 
      - backend
  hitch:
    image: zazukoians/hitch:1.5.0
    hostname: docker-hitch
    environment:
      - HITCH_PEM=/etc/ssl/hitch/self-signed.pem
      - HITCH_PARAMS=--frontend=[*]:8443 --backend=[varnish]:8082 --alpn-protos="h2, http/1.1" --write-proxy-v2
      - HITCH_CIPHER=EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    volumes:
      - ${PWD}/log/hitch-front:/var/log
      - ${PWD}/etc/hitch:/etc/hitch
      - ${PWD}/etc/ssl-managed:/etc/ssl/hitch/
    ports:
     - "8443:8443" 
    depends_on:
      - varnish
  nginx:
    image: nginx:latest
    hostname: docker-nginx
    volumes:
      - ${PWD}/log/nginx:/var/log/nginx
      - ${PWD}/etc/nginx:/etc/nginx
      - ${PWD}/etc/ssl-managed:/etc/ssl-managed
    ports:
      - "8444:8444"
    depends_on: 
      - varnish
  haproxy:
    image: haproxy:1.9.5
    hostname: docker-haproxy
    volumes:
      - ${PWD}/log/haproxy:/var/log
      - ${PWD}/etc/haproxy:/usr/local/etc/haproxy
      - ${PWD}/etc/ssl-managed:/etc/ssl-managed
      - ${PWD}/run:/tmp/run
    ports:
      - "8084:8084"
      - "8445:8445"
      - "8446:8446"
      - "8447:8447"
      - "8448:8448"
    depends_on:
      - varnish
  envoy:
    image: envoyproxy/envoy
    ports:
      - "8449:8449"
      - "8001:8001"
    volumes:
      - ${PWD}/etc/envoy/:/etc/envoy/
      - ${PWD}/etc/ssl-managed:/etc/ssl-managed
    depends_on: 
      - varnish
  traefik:
    image: 
    ports: 
      - 8450:8450
    volumes:
      - ${PWD}/etc/traefik/:/etc/traefik/
      - ${PWD}/etc/ssl-managed:/etc/ssl-managed
    depends_on:
      - varnish
  backend:
    image: owasp/modsecurity-crs
    environment:
      - PARANOIA=1
    ports:
      - "8080:80"
  benchmarker:
    image: centminmod/docker-ubuntu-nghttp2
    network_mode: host
    volumes:
      - ${PWD}/bin:/tmp/bin
    command: ["/bin/bash", "/tmp/bin/benchmark.sh"]
    depends_on: 
      - envoy
      - haproxy
      - nginx
      - hitch





