version: "3"

services:
  varnish:
    image: emgag/varnish:6.0.3-2 
    hostname: docker-varnish
    volumes:
      - ${PWD}/etc/varnish:/etc/varnish
      - ${PWD}/run:/tmp/run/
    environment:
      - VARNISH_DAEMON_OPTS=-p feature=+http2 -a :81,PROXY -a /tmp/run/varnish.sock,PROXY
    ports:
     - "80:80"
     - "81:81"
  hitch:
    image: zazukoians/hitch:1.5.0
    hostname: docker-hitch
    environment:
      - HITCH_PEM=/etc/ssl/hitch/self-signed.pem
      - HITCH_PARAMS=--frontend=[*]:443 --backend=[varnish]:81 --alpn-protos="h2, http/1.1" --write-proxy-v2
      - HITCH_CIPHER=EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    volumes:
      - ${PWD}/log/hitch-front:/var/log
      - ${PWD}/etc/hitch:/etc/hitch
      - ${PWD}/etc/ssl-managed:/etc/ssl/hitch/
    ports:
     - "443:443" 
  nginx:
    image: nginx:latest
    hostname: docker-nginx
    volumes:
      - ${PWD}/log/nginx:/var/log/nginx
      - ${PWD}/etc/nginx:/etc/nginx
      - ${PWD}/etc/ssl-managed:/etc/ssl-managed
    ports:
      - "444:444"
  haproxy:
    image: haproxy:1.9.5
    hostname: docker-haproxy
    volumes:
      - ${PWD}/log/haproxy:/var/log
      - ${PWD}/etc/haproxy:/usr/local/etc/haproxy
      - ${PWD}/etc/ssl-managed:/etc/ssl-managed
      - ${PWD}/run:/tmp/run
    ports:
     - "82:82"
     - "445:445"
     - "446:446"
     - "447:447"
     - "448:448"
  envoy:
    image: envoyproxy/envoy
    port:
      - "10000:10000"
    volumes:
      - ${PWD}/etc/envoy/:/etc/envoy/
  backend:
    image: owasp/modsecurity-crs
    environment:
      - PARANOIA=1
    ports:
      - "8080:80"

